---
http_interactions:
- request:
    method: get
    uri: https://hawkular.torii.gva.redhat.com/hawkular/inventory/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - hawkular.torii.gva.redhat.com
      Authorization: 'Basic PCU9IHVzZXJuYW1lICU+OjwlPSBwYXNzd29yZCAlPg==

'
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.6.3
      Date:
      - Wed, 10 Aug 2016 22:36:02 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '234'
      Connection:
      - keep-alive
      X-Powered-By:
      - Undertow/1
      Strict-Transport-Security:
      - max-age=31536000
    body:
      encoding: UTF-8
      string: |-
        {
          "Implementation-Version" : "0.17.3.Final",
          "Built-From-Git-SHA1" : "144a571ea8f3a819737c2937ccc0492d8a116bb4",
          "Inventory-Implementation" : "org.hawkular.inventory.impl.tinkerpop.TinkerpopInventory",
          "Initialized" : "true"
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:36:03 GMT
- request:
    method: get
    uri: https://hawkular.torii.gva.redhat.com/hawkular/inventory/traversal/type=f
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - hawkular.torii.gva.redhat.com
      Authorization: 'Basic PCU9IHVzZXJuYW1lICU+OjwlPSBwYXNzd29yZCAlPg==

'
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.6.3
      Date:
      - Wed, 10 Aug 2016 22:36:05 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '269'
      Connection:
      - keep-alive
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Pragma:
      - no-cache
      X-Total-Count:
      - '1'
      Link:
      - <http://hawkular.torii.gva.redhat.com/hawkular/inventory/traversal/type=f>;
        rel="current"
      Strict-Transport-Security:
      - max-age=31536000
    body:
      encoding: UTF-8
      string: |-
        [ {
          "path" : "/t;hawkular/f;71daaa4b-da76-4373-8753-68279f33a884",
          "properties" : {
            "__identityHash" : "d29de2f66088bd2d4f237e3ee75ec4f3da515a"
          },
          "identityHash" : "d29de2f66088bd2d4f237e3ee75ec4f3da515a",
          "id" : "71daaa4b-da76-4373-8753-68279f33a884"
        } ]
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:36:06 GMT
recorded_with: VCR 3.0.3
