# possible values:
# https://github.com/bbatsov/rubocop/blob/master/config/

AllCops:
  TargetRubyVersion: 2.2.0
  DisplayCopNames: true
  Exclude:
    - Gemfile.dev.rb

#
# Overrides
#
CyclomaticComplexity:
  Max: 9
  Severity: refactor
PerceivedComplexity:
  Max: 9
Metrics/LineLength:
  Max: 120
Metrics/ParameterLists:
  Max: 8

#
# Enabled/Disabled
#
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Lint/RescueWithoutErrorClass:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - hawkularclient.gemspec
ModuleLength:
  Enabled: false
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/ClassAndModuleChildren:
  Enabled: false
Style/SignalException:
  Enabled: false
