hawkular:
  # !! WARNING !! FIXME !! TODO !!
  # Reset to hawkular/hawkular-services:latest before merging in master
  image: "jotak/hawkular-services:0.40.0.Final-SNAPSHOT"
  ports:
    - "8080:8080"
    - "8443:8443"
    - "9990:9990"
  links:
    - myCassandra
  volumes:
    - /tmp/opt/hawkular/server:/opt/data:Z
  environment:
    - CASSANDRA_NODES=myCassandra
    - ADMIN_TOKEN
myCassandra:
  image: cassandra:3.0.12
  environment:
    - CASSANDRA_START_RPC=true
