hawkular:
  image: "hawkular/hawkular-services:latest"
  ports:
    - "8080:8080"
    - "8443:8443"
    - "9990:9990"
  links:
    - myCassandra
  volumes:
    - /tmp/opt/hawkular/server:/opt/data
  environment:
    - CASSANDRA_NODES=myCassandra
    - ADMIN_TOKEN=123-456-789
myCassandra:
  image: cassandra:3.0.12
  environment:
    - CASSANDRA_START_RPC=true
