---
http_interactions:
- request:
    method: get
    uri: http://localhost:8080/hawkular/metrics/strings/tags/module:inventory,feed:*
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Authorization: |
        Basic PCU9IHN1cGVyX3NlY3JldF91c2VybmFtZSAlPjo8JT0gc3VwZXJfc2VjcmV0
        X3Bhc3N3b3JkICU+
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 25 Apr 2017 15:07:03 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '48'
    body:
      encoding: UTF-8
      string: '{"feed":["<%= feed_uuid %>"],"module":["inventory"]}'
    http_version: 
  recorded_at: Tue, 25 Apr 2017 15:07:03 GMT
recorded_with: VCR 3.0.3
