---
http_interactions:
- request:
    method: get
    uri: http://localhost:8080/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Authorization: |
        Basic PCU9IHN1cGVyX3NlY3JldF91c2VybmFtZSAlPjo8JT0gc3VwZXJfc2VjcmV0
        X3Bhc3N3b3JkICU+
  response:
    status:
      code: 200
      message: OK
    headers:
      Connection:
      - keep-alive
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '150'
      Date:
      - Tue, 25 Apr 2017 15:07:05 GMT
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.26.0.Final","Built-From-Git-SHA1":"fe3ef3ccc36a0c85bcdbf3e96aae8d36a636f7f2","Cassandra":"up"}'
    http_version: 
  recorded_at: Tue, 25 Apr 2017 15:07:05 GMT
recorded_with: VCR 3.0.3
