---
http_interactions:
- request:
    method: post
    uri: http://localhost:8080/hawkular/api/urls
    body:
      encoding: UTF-8
      string: '{"url":"http://bsd.de"}'
    headers:
      Accept:
      - "*/*"
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '23'
      Host:
      - localhost:8080
      Authorization: |
        Basic PCU9IHN1cGVyX3NlY3JldF91c2VybmFtZSAlPjo8JT0gc3VwZXJfc2VjcmV0
        X3Bhc3N3b3JkICU+
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Expires:
      - '0'
      Connection:
      - keep-alive
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Content-Length:
      - '0'
      Date:
      - Tue, 02 May 2017 19:41:32 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 02 May 2017 19:41:32 GMT
recorded_with: VCR 3.0.3
