---
http_interactions:
- request:
    method: get
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/tags/module:inventory,feed:*
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - localhost:8080
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 02 May 2017 19:41:32 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '63'
    body:
      encoding: UTF-8
      string: '{"feed":["9a8378da4a7d","1adc16c1551d"],"module":["inventory"]}'
    http_version: 
  recorded_at: Tue, 02 May 2017 19:41:32 GMT
recorded_with: VCR 3.0.3
